adding id3 tagging to kexpcorder

diff --git a/kexpcorder b/kexpcorder
--- a/kexpcorder
+++ b/kexpcorder
@@ -1,7 +1,21 @@
 #!/bin/bash
 
-FILENAME=kexp-`date "+%Y-%m-%d_%H%M"`.mp3
-$HOME/bin/vlcorder http://live-mp3-128.kexp.org:80/kexp128.mp3 $HOME/tmp/$FILENAME
+if [ $# -ne 1 ]
+then
+    echo "ERROR: Incorrect Usage"
+    echo "kexpcorder <show-name>"
+    exit 1
+fi
+
+SHOW=$1
+YEAR=`date "+%Y"`
+DATETIME=`date "+%m-%d_%H%M"`
+FILENAME=$SHOW-$YEAR-$DATETIME.aac
+
+# record the stream via vlc
+$HOME/bin/vlcorder http://live-aacplus-64.kexp.org/kexp64.aac $HOME/tmp/$FILENAME
+# update id3 metadata
+id3 -a "KEXP $SHOW" -l "$SHOW $YEAR" -t "$SHOW $DATETIME" -g "Acid" $HOME/tmp/$FILENAME
 
 mv $HOME/tmp/$FILENAME $HOME/GDrive/KEXP
 
